export const Languages_Tools = [
  {
    p: "Languages",
    logos: [
      "logo/html.svg",
      "logo/css3.svg",
      "logo/javascript.svg",
      "logo/typescript.svg",
      "logo/sass.svg",
    ],
    logo_name: ["html", "css3", "javascript", "typescript", "sass"],
  },
  {
    p: "Frameworks & Libraries",
    logos: [
      "logo/react.svg",
      "logo/next.svg",
      "logo/redux.svg",
      "logo/react-query.svg",
      "logo/tailwindcss.svg",
      "logo/chakra-ui.svg",
      "logo/bootstrap.svg",
      "logo/framer-motion.svg",
      "logo/formik.svg",
      "logo/swiper.svg",
    ],
    logo_name: [
      "react.js",
      "next.js",
      "redux",
      "reactQuery",
      "tailwindcss",
      "chakraUi",
      "bootstrap",
      "framerMotion",
      "formik",
      "swiper",
    ],
  },
  {
    p: "Tools",
    logos: ["logo/github.svg", "logo/git.svg", "logo/vite.svg"],
    logo_name: ["github", "git", "vite"],
  },
];
