export const Languages_Tools = [
  {
    p: "Languages",
    logos: [
      "logo/html.svg",
      "logo/css3.svg",
      "logo/javascript.svg",
      "logo/typescript.svg",
      "logo/sass.svg",
    ],
    logo_name: ["html", "css3", "javascript", "typescript", "sass"],
  },
  {
    p: "Technologies",
    logos: [
      "logo/react.svg",
      "logo/chakra-ui.svg",
      "logo/tailwindcss.svg",
      // "logo/bootstrap.svg",
      "logo/framer-motion.svg",
      "logo/formik.svg",
      "logo/swiper.svg",
      "logo/github.svg",
      "logo/git.svg",
      "logo/vite.svg",
    ],
    logo_name: [
      "reactjs",
      "chakraUi",
      "tailwindcss",
      // "bootstrap",
      "framerMotion",
      "formik",
      "swiper",
      "github",
      "git",
      "vite",
    ],
  },
  {
    p: "State Manegment",
    logos: ["logo/redux.svg", "logo/react-query.svg"],
    logo_name: ["redux", "reactQuery"],
  },
];